# Generated by Django 5.2.6 on 2025-09-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_uploadeddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='name',
            field=models.CharField(default='Untitled', max_length=255),
            preserve_default=False,
        ),
    ]
